// Code generated by 'yaegi extract github.com/karagenc/kopyat'. DO NOT EDIT.

package symbols

import (
	"github.com/karagenc/kopyat"
	"github.com/karagenc/kopyat/internal/scripting/ctx"
	"reflect"
)

func init() {
	Symbols["github.com/karagenc/kopyat/kopyat"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"GetContext": reflect.ValueOf(kopyat.GetContext),

		// type definitions
		"BackupContext":          reflect.ValueOf((*kopyat.BackupContext)(nil)),
		"Context":                reflect.ValueOf((*kopyat.Context)(nil)),
		"IfileGenerationContext": reflect.ValueOf((*kopyat.IfileGenerationContext)(nil)),

		// interface wrapper definitions
		"_Context": reflect.ValueOf((*_github_com_karagenc_kopyat_Context)(nil)),
	}
}

// _github_com_karagenc_kopyat_Context is an interface wrapper for Context type
type _github_com_karagenc_kopyat_Context struct {
	IValue           interface{}
	WBackup          func() (c *ctx.BackupContext, ok bool)
	WIfileGeneration func() (c *ctx.IfileGenerationContext, ok bool)
}

func (W _github_com_karagenc_kopyat_Context) Backup() (c *ctx.BackupContext, ok bool) {
	return W.WBackup()
}
func (W _github_com_karagenc_kopyat_Context) IfileGeneration() (c *ctx.IfileGenerationContext, ok bool) {
	return W.WIfileGeneration()
}
