// Code generated by 'yaegi extract github.com/mitchellh/go-homedir'. DO NOT EDIT.

package symbols

import (
	"github.com/mitchellh/go-homedir"
	"reflect"
)

func init() {
	Symbols["github.com/mitchellh/go-homedir/homedir"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Dir":          reflect.ValueOf(homedir.Dir),
		"DisableCache": reflect.ValueOf(&homedir.DisableCache).Elem(),
		"Expand":       reflect.ValueOf(homedir.Expand),
		"Reset":        reflect.ValueOf(homedir.Reset),
	}
}
