// Code generated by 'yaegi extract github.com/tomruk/kopyaship/scripting/s'. DO NOT EDIT.

package scripting

import (
	"github.com/tomruk/kopyaship/scripting/s"
	"reflect"
)

func init() {
	symbols["github.com/tomruk/kopyaship/scripting/s/s"] = map[string]reflect.Value{
		// type definitions
		"Runner": reflect.ValueOf((*s.Runner)(nil)),

		// interface wrapper definitions
		"_Runner": reflect.ValueOf((*_github_com_tomruk_kopyaship_scripting_s_Runner)(nil)),
	}
}

// _github_com_tomruk_kopyaship_scripting_s_Runner is an interface wrapper for Runner type
type _github_com_tomruk_kopyaship_scripting_s_Runner struct {
	IValue interface{}
	WRun   func()
}

func (W _github_com_tomruk_kopyaship_scripting_s_Runner) Run() {
	W.WRun()
}
